apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operators.opdev.io/v1alpha1",
          "kind": "CertManagerDeployment",
          "metadata": {
            "name": "cluster"
          },
          "spec": {
            "version": "v1.3.1"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.7.1+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: certmanagerdeployment-operator.v0.0.1-alpha3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CertManagerDeployment is the Schema for the certmanagerdeployments API
      displayName: Cert-Manager Deployment
      kind: CertManagerDeployment
      name: certmanagerdeployments.operators.opdev.io
      resources:
      - kind: CustomResourceDefinition
        name: certificaterequests.cert-manager.io
        version: v1
      - kind: CustomResourceDefinition
        name: certificates.cert-manager.io
        version: v1
      - kind: CustomResourceDefinition
        name: challenges.acme.cert-manager.io
        version: v1
      - kind: CustomResourceDefinition
        name: clusterissuers.cert-manager.io
        version: v1
      - kind: CustomResourceDefinition
        name: issuers.cert-manager.io
        version: v1
      - kind: CustomResourceDefinition
        name: orders.acme.cert-manager.io
        version: v1
      version: v1alpha1
  description: Manage your Cert-Manager installation alongside complementary controllers in OpenShift
  displayName: Cert-Manager Deployment Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations/finalizers
          - validatingwebhookconfigurations/finalizers
          verbs:
          - update
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - list
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - get
          - list
          - update
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - namespaces
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces/finalizers
          - serviceaccounts/finalizers
          - services/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - operators.opdev.io
          resources:
          - certmanagerdeployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - operators.opdev.io
          resources:
          - certmanagerdeployments/finalizers
          verbs:
          - update
        - apiGroups:
          - operators.opdev.io
          resources:
          - certmanagerdeployments/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          verbs:
          - bind
          - create
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings/finalizers
          - clusterroles/finalizers
          - rolebindings/finalizers
          - roles/finalizers
          verbs:
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cmd-operator-sa
      deployments:
      - name: cmd-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/opdev/certmanagerdeployment-operator:v0.0.1-alpha3
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 300Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
              serviceAccountName: cmd-operator-sa
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cmd-operator-sa
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cert-manager
  - tls
  - podrefresh
  - workloadrefresh
  links:
  - name: Certmanagerdeployment Operator
    url: https://certmanagerdeployment-operator.domain
  maintainers:
  - email: josegonzalez89@gmail.com
    name: Jose R. Gonzalez
  maturity: alpha
  provider:
    name: The OpDev Team
    url: https://github.com/opdev/
  version: 0.0.1-alpha3
