name: Publish Operator Bundle Image to Quay
on:  
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-and-publish:
    # Skip tags not associated with the main branch
    if: github.event.base_ref == 'refs/heads/main'
    env:
      REGISTRY: quay.io
      NAMESPACE: opdev
      IMAGE: certmanagerdeployment-operator-bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag reference from environment
        # TODO: consider using `git tag --points-at HEAD`
        run: |
          echo RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3) >> $GITHUB_ENV

      - name: Build and tag container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}
          tags: ${{ env.RELEASE_TAG }}
          dockerfiles: ./bundle.Dockerfile

      - name: Publish container image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.NAMESPACE }}/${{ env.IMAGE }}
          tags: ${{ env.RELEASE_TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_QUAY_USER_NAME }}
          password: ${{ secrets.REGISTRY_QUAY_TOKEN }}
